export var type = {
  "Piece wolnostojace": ["Dovre-w", "Defro-w", "Kratki-w"],
  "Wkłady powietrzne": [
    "Brunner-p",
    "KFD-p",
    "Kratki-p",
    "Schmid-p",
    "Romotop-p",
    "Defro-p",
    "Spartherm-p",
  ],
  "Wkłady z płaszczem wodnym": [
    "Brunner-pw",
    "Defro-pw",
    "Kratki-pw",
    "Schmid-pw",
    "Spartherm-pw",
    "Romotop-pw",
  ],
};
export var manufacturer = {
  //Wolnostojące
  "Defro-w": [
    "HOME ORBIS",
    "HOME ORBIS LOG",
    "HOME ORBIS TOP",
    "HOME SOLUM",
    "HOME SOLUM LOG",
    "HOME SOLUM TOP",
    "HOME IGNIS",
    "HOME CUBE",
    "HOME ORTI",
    "HOME OVAL",
    "HOME QUADROOM",
    "HOME PICO",
  ],
  "Dovre-w": [
    "PIEC 525 CB",
    "PIEC 640 GM",
    "PIEC ASTRO 2/P",
    "PIEC ASTRO 3 CB/WB",
    "PIEC ASTRO 4 CBP",
    "PIEC BOLD 300",
    "PIEC BOLD 400",
    "PIEC BOW",
    "PIEC BOW P",
    "PIEC BOW WB",
    "PIEC BRUT 100",
    "PIEC ROCK 350 TB",
    "PIEC ROCK 350 WB",
    "PIEC ROCK 500 TB",
    "PIEC ROCK 500 WB",
    "PIEC SENSE 103",
    "PIEC SENSE 203",
    "PIEC SENSE 300",
    "PIEC SENSE 303",
    "PIEC SENSE 403",
    "PIEC TAI 55M",
    "PIEC VINTAGE 30",
    "PIEC VINTAGE 30 TB",
    "PIEC VINTAGE 30 WB",
    "PIEC VINTAGE 35",
    "PIEC VINTAGE 50",
    "PIEC VINTAGE 50 TB",
    "PIEC VINTAGE 50 WB",
  ],
  "Kratki-w": [
    "ANTARES 10",
    "KOZA K10 fi 130 z ASDP",
    "KOZA K10 fi 130 z Turbofanem",
    "KOZA K10 fi 150 z ASDP",
    "KOZA K10 fi 150 z Turbofanem",
    "KOZA K5 fi 130",
    "KOZA K5 fi 150",
    "KOZA K6 PW fi 130",
    "KOZA K6 fi 130 z Turbofanem",
    "Koza K6 z wylotem spalin fi 150 z wymiennikiem wodnym",
    "KOZA K6 fi 150 z Turbofanem",
    "KOZA K7 z ASDP",
    "KOZA K7 z Turbofanem",
    "KOZA K8 z ASDP",
    "KOZA K8 tunel",
    "KOZA K8 z Turbofanem",
    "KOZA K9 fi 130 z ASDP",
    "Koza K5 z wylotem spalin fi 150",
    "WHISKEY 2 biały z certyfikatem TÜV",
    "WHISKEY 2 granito z certyfikatem TÜV",
    "WHISKEY biały z certyfikatem TÜV",
    "WHISKEY granito z certyfikatem TÜV",
    "BIOMISA MINI czarny z certyfikatem TÜV",
    "BIOMISA czarny z certyfikatem TÜV",
    "FALCON 9 W",
    "FOXTROT czarny z certyfikatem TÜV",
    "HOTEL biały z certyfikatem TÜV",
    "HOTEL MINI biały z certyfikatem TÜV",
    "HOTEL MINI czarny z certyfikatem TÜV",
    "HOTEL czarny z certyfikatem TÜV",
    "INDIA czarny z certyfikatem TÜV",
    "INDIA MAX czarny z certyfikatem TÜV",
    "INDIA MINI czarny z certyfikatem TÜV",
    "JUNO 12 panel biały",
    "JUNO 12 panel czarny",
    "KOZA AB S/2",
    "Koza AB STAL 2  z wylotem spalin fi 150 z panelami kaflowym",
    "KOZA AB S/DR",
    "Koza AB STAL DR z wylotem spalin fi 150 z panelami kaflowymi",
    "KOZA AB S/N/DR",
    "Koza AB STAL NOGA DR z wylotem spalin fi 150 z panelami kaflowymi",
    "KOZA AB S/N/O/DR GLASS",
    "Koza AB STAL NOGA OBROTOWA z wylotem spalin fi 150, glasem i panelami kaflowymi",
    "KOZA AB S/N/O/DR",
    "KOZA ORBIT",
    "KOZA PICARD",
    "Safari EQ",
    "KOZA VEGA fi 150",
    "FALCON 9",
    "FALCON 9 VIEW",
    "KOZA AB",
    "Koza AB ENYO STAL",
    "KOZA AB S/2",
    "Koza AB S CASTO",
    "KOZA AB S/DR",
    "Koza AB STAL",
    "KOZA AB S/N/DR",
    "KOZA AB S/N/DR GLASS",
    "KOZA AB S/N/O/DR",
    "KOZA AB S/N/O/DR GLASS",
    "Alfa EQ",
    "Koza CASTO",
    "Koza Dark EQ",
    "KOZA EPSILON",
    "KOZA K10 fi 130",
    "KOZA K10 fi 150",
    "KOZA K5 S",
    "KOZA K5 S/N",
    "KOZA K5 S z wnęką na drewno",
    "KOZA K5 S z zamykaną wnęką na drewno",
    "KOZA K6 fi 130",
    "KOZA K6 fi 130 z ASDP",
    "KOZA K6 fi 150",
    "KOZA K6 fi 150 z ASDP",
    "KOZA K7",
    "KOZA K8",
    "KOZA K9 fi 130",
    "KOZA K9 fi 130 z Turbofanem",
    "KOZA K9 fi 150",
    "KOZA K9 fi 150 z ASDP",
    "KOZA K9 PW fi 150",
    "KOZA K9 fi 150 z Turbofanem",
    "Koza LC11 z wylotem spalin na plecach",
    "Koza LC11/n na nodze",
    "Koza LC11 z wylotem spalin do góry",
    "Koza LC7",
    "Koza LC8",
    "Koza Mega EQ",
    "KOZA PROTON",
    "KOZA TITAN",
    "KOZA TITAN GLASS",
    "KOZA TITAN GLASS panoramiczny",
    "KOZA VEGA fi 130",
    "THOR 8",
    "THOR czarny termotec",
    "THOR 8 VIEW",
  ],

  //Powietrzne
  "Brunner-p": [
    "Kompakt Kamin Flach 51/55 Drehtür",
    "Kompakt Kamin Flach 51/55 Schiebetür",
    "Kompakt Kamin Flach 51/67 Drehtür",
    "Kompakt Kamin Flach 51/67 Schiebetür",
    "Kompakt Kamin Flach 57/55 Drehtür",
    "Kompakt Kamin Flach 57/55 Schiebetür",
    "Kompakt Kamin Flach 57/67 Drehtür",
    "Kompakt Kamin Flach 57/67 Schiebetür",
    "Stil Kamin Flach 51/67",
    "Stil Kamin Flach 53/88",
    "Stil Kamin Flach 53/88 K",
    "Stil Kamin Flach 62/76",
    "Stil Kamin Flach 62/76 K",
    "Stil Kamin Flach 75/90",
    "Kamin Architektur Eck 38/86",
    "Kamin Architektur Eck 45/101",
    "Kamin Architektur Eck 53/121",
    "Kamin Architektur 53/135",
    "Kamin Architektur 53/166",
    "Kamin Eck 42/42/42",
    "Kamin Eck 42/57/30",
    "Kamin Eck 51/52/52",
    "Kamin Eck 57/52/52",
    "Kamin Eck 42/57/30 drzwi unoszone",
    "Kamin Eck 51/52/52 drzwi unoszone",
    "Kamin Eck 57/52/52 drzwi unoszone",
    "Kamin Eck 57/67/44 drzwi unoszone",
    "Kamin Eck 57/82/48 drzwi unoszone",
    "Kamin Eck 70/33/33 drzwi unoszone",
    "Architektur Eck 38/86/36",
    "Architektur Eck 45/101/40",
    "Architektur Eck 45/67/44",
    "Architektur Eck 45/82/48",
    "Architektur Eck 53/121/50",
    "Panorama 42/42/42/42",
    "Panorama 51/25/101/25",
    "Panorama 57/40/60/40 von Brunner",
    "Panorama 51/66/50/66",
    "Panorama 51/88/50/88",
    "Panorama 57/25/121/25",
    "Panorama 57/25/60/25",
    "Panorama 57/25/85/25",
    "Panorama 57/40/60/40",
    "Panorama 57/40/85/40",
    "Panorama 70/25/40/25",
    "Tunnel 51/67",
    "Tunnel 53/88",
    "Tunnel 62/76",
    "Tunnel 75/90",
    "Tunnel Architektur 38/86",
    "Tunnel Architektur 45/101",
    "Tunnel Architektur 53/121",
    "Tunnel Architektur 53/135",
    "Tunnel Architektur 53/166",
  ],
  "Defro-p": [
    "HOME INTRA XSM",
    "HOME INTRA SM",
    "HOME INTRA ME",
    "HOME INTRA LA",
    "HOME INTRA SM BL MINI",
    "HOME INTRA SM BP MINI",
    "HOME INTRA SM BL",
    "HOME INTRA SM BP",
    "HOME INTRA ME BL",
    "HOME INTRA ME BP",
    "HOME INTRA SM G",
    "HOME INTRA ME G",
    "HOME INTRA LA G",
    "HOME INTRA SM BL MINI G",
    "HOME INTRA SM BP MINI G",
    "HOME INTRA SM BL BL G",
    "HOME INTRA SM BP G",
    "HOME INTRA ME BP G",
    "HOME INTRA ME BL G",
    "HOME INTRA SM SLIM",
    "HOME INTRA ME SLIM",
    "HOME INTRA SM BL SLIM",
    "HOME INTRA ME BL SLIM",
    "HOME INTRA SM BP SLIM",
    "HOME INTRA ME BP SLIM",
    "HOME IMPULS SM",
    "HOME IMPULS ME",
    "HOME IMPULS SM BL",
    "HOME IMPULS ME BL",
    "HOME IMPULS SM BP",
    "HOME IMPULS ME BP",
    "HOME INTRA SM T",
    "HOME INTRA ME T",
    "HOME INTRA LA T",
    "HOME INTRA SM T G",
    "HOME INTRA ME T G",
    "HOME INTRA LA T G",
    "HOME INTRA SM SLIM G",
    "HOME INTRA ME SLIM G",
    "HOME INTRA SM BL SLIM G",
    "HOME INTRA ME BL SLIM G",
    "HOME INTRA SM BP SLIM G",
    "HOME INTRA ME BP SLIM G",
    "HOME INTRA XSM C G",
    "HOME INTRA SM C G",
    "HOME PORTAL ME G",
    "HOME PORTAL ME ",
    "HOME INTRA SM C",
    "HOME INTRA ME C G",
    "HOME INTRA XLA G",
  ],
  "Kratki-p": [
    "AMELIA 13 EKO",
    "AMELIA 25 gilotyna",
    "AMELIA 25 lewy",
    "AMELIA 25 lewy BS",
    "AMELIA 25 lewy BS DECO",
    "AMELIA 25 lewy BS gilotyna",
    "AMELIA 25 lewy / prawy",
    "AMELIA 25 LUX",
    "AMELIA 25 prawy",
    "AMELIA 25 prawy BS",
    "AMELIA 25 prawy BS DECO",
    "AMELIA 25 prawy BS gilotyna",
    "AMELIA 25 (podwójna szyba)",
    "ANTEK 10 gilotyna",
    "BASIA 15",
    "ERYK 12 700",
    "ERYK 12 DECO",
    "ERYK 12 LUX",
    "FELIX 16 DECO",
    "FELIX 16 gilotyna",
    "FELIX 16 LUX",
    "FRANEK 10",
    "FRANEK 12",
    "FRANEK 14",
    "MAJA 8 lewy BS gilotyna",
    "MAJA 8 lewy / prawy",
    "MAJA 8 prawy BS gilotyna",
    "MAJA 15 Wieża",
    "OLIWIA 18 gilotyna",
    "OLIWIA 18 lewy",
    "OLIWIA 18 lewy BS",
    "OLIWIA 18 lewy BS DECO",
    "OLIWIA 18 lewy BS gilotyna",
    "OLIWIA 18 lewy / prawy",
    "OLIWIA 18 prawy",
    "OLIWIA 18 prawy BS",
    "OLIWIA 18 prawy BS DECO",
    "OLIWIA 18 prawy BS gilotyna",
    "WIKTOR 14 gilotyna",
    "ZUZIA 16 700",
    "ZUZIA 16 gilotyna",
    "ZUZIA 16 lewy",
    "ZUZIA 16 lewy / prawy",
    "ZUZIA 16 lewy / prawy / tunel",
    "ZUZIA 16 lewy / tunel",
    "ZUZIA 16 LUX",
    "ZUZIA 16 prawy",
    "ZUZIA 16 prawy BS gilotyna",
    "ZUZIA 16 (podwójna szyba)",
    "ZUZIA 16 prawy / tunel",
    "ZUZIA 16 tunel",
    "BLANKA 12 lewy BS",
    "BLANKA 14",
    "BLANKA 8 kafel czarny",
    "BLANKA 8 kafel krem",
    "BLANKA 8 lewy / prawy BS",
    "BLANKA 8",
    "BLANKA 12 lewy BS",
    "BLANKA 14",
    "BLANKA 8 kafel czarny",
    "BLANKA 8 kafel krem",
    "BLANKA 8 lewy / prawy BS",
    "BLANKA 8",
    "ARKE 70",
    "ARKE 75",
    "ARKE 85",
    "ARKE 95",
    "LUCY 12 (podwójna szyba)",
    "LUCY 12 SLIM (podwójna szyba)",
    "LUCY 14 (podwójna szyba)",
    "LUCY 14 SLIM (podwójna szyba)",
    "LUCY 15",
    "LUCY 16",
    "MB 120 gilotyna",
    "MBA 17 lewy BS",
    "MBA 17 lewy BS gilotyna szyba gięta",
    "MBA 17 lewy BS szyba gięta",
    "MBA 17 prawy BS gilotyna szyba gięta",
    "MBA 17 prawy BS szyba gięta",
    "MBA 17",
    "MBA 17 (podwójna szyba)",
    "MBM 10 lewy BS",

    "MBM 10 lewy BS gilotyna szyba gięta",
    "MBM 10 lewy BS szyba gięta",
    "MBM 10 prawy BS",

    "MBM 10 prawy BS gilotyna szyba gięta",

    "MBM 10 prawy BS szyba gięta",
    "MBM 10 (podwójna szyba)",

    "MBN/680/L/BS",
    "MBN/680/P/BS",
    "MBN 12 lewy BS",
    "MBN 12 lewy BS szyba gięta",
    "MBN 12 prawy BS",
    "MBN 12 prawy BS szyba gięta",
    "MBO 15 lewy BS",
    "MBO 15 lewy BS gilotyna",
    "MBO 15 lewy BS gilotyna szyba gięta",
    "MBO 15 lewy BS szyba gięta",
    "MBO 15 prawy BS",
    "MBO 15 prawy BS gilotyna",
    "MBO 15 prawy BS gilotyna szyba gięta",
    "MBO 15 prawy BS szyba gięta",
    "MBO 15",
    "MBZ 13 gilotyna",
    "MBZ 13 gilotyna (podwójna szyba)",
    "MBZ gilotyna DG czarny",
    "MBZ 13 lewy BS",
    "MBZ 13 lewy BS gilotyna szyba gięta",
    "MBZ 13 lewy BS szyba gięta",
    "MBZ 13 prawy BS",
    "MBZ 13 prawy BS gilotyna szyba gięta",
    "MBN/680/L/BS",
    "MBN/680/P/BS",
    "MBN 12 lewy BS",
    "MBN 12 lewy BS szyba gięta",
    "MBN 12 prawy BS",
    "MBN 12 prawy BS szyba gięta",
    "MBO 15 lewy BS",
    "MBO 15 lewy BS gilotyna",
    "MBO 15 lewy BS gilotyna szyba gięta",
    "MBO 15 lewy BS szyba gięta",
    "MBO 15 prawy BS",
    "MBO 15 prawy BS gilotyna",
    "MBO 15 prawy BS gilotyna szyba gięta",
    "MBO 15 prawy BS szyba gięta",
    "MBO 15",
    "MBZ 13 gilotyna",
    "MBZ 13 gilotyna (podwójna szyba)",
    "MBZ gilotyna DG czarny",
    "MBZ 13 lewy BS",
    "MBZ 13 lewy BS gilotyna szyba gięta",
    "MBZ 13 lewy BS szyba gięta",
    "MBZ 13 prawy BS",
    "MBZ 13 prawy BS gilotyna szyba gięta",
    "MILA 16 gilotyna",
    "MILA 16",
    "MILA 16 (podwójna szyba)",
    "MILA 16 tunel",
    "MILA 16 tunel gilotyna",
    "NADIA 10 (podwójna szyba)",
    "NADIA 10 gilotyna",
    "NADIA 12 gilotyna",
    "NADIA 13 (podwójna szyba)",
    "NADIA 14 (podwójna szyba)",
    "NADIA 8 (podwójna szyba)",
    "NADIA 9 (podwójna szyba)",
    "NADIA 8 kafel MILANO",
    "NBC 8 lewy / prawy BS gilotyna",
    "NBC 9 lewy / prawy BS gilotyna",
    "NBC 7 lewy / prawy BS gilotyna",
    "NBC 10 lewy / prawy BS gilotyna",
    "NBU 11 lewy / prawy BS gilotyna",
    "VN 480/480 lewy BS gilotyna",
    "VN 610/430 lewy BS gilotyna",
    "VN 700/480 lewy BS gilotyna",
    "VN 810/410 lewy BS gilotyna",
    "VN 480/480 prawy BS gilotyna",
    "VN 610/430 prawy BS gilotyna",
    "VN 700/480 prawy BS gilotyna",
    "VN 810/410 prawy BS gilotyna",
    "WK 440 kafel krem",
    "AMELIA 25 DECO",
    "AMELIA 25",
    "ANTEK 10 DECO",
    "ANTEK 10",
    "BASIA 15",
    "BLANKA 12",
    "BLANKA 12 lewy / prawy BS",
    "BLANKA 12 prawy BS",
    "BLANKA 8 lewy BS",
    "BLANKA 8 prawy BS",
    "ERYK 12",
    "FELIX 16",
    "JAŚ 6",
    "LUCY 12",
    "LUCY 12 lewy BS",
    "LUCY 12 prawy BS",
    "LUCY 12 SLIM",
    "LUCY 12 SLIM lewy BS",
    "LUCY 12 SLIM prawy BS",
    "LUCY 12 tunel",
    "LUCY 12 tunel (podwójna szyba)",
    "LUCY 14",
    "LUCY 14 lewy BS",
    "LUCY 14 prawy BS",
    "LUCY 14 SLIM",
    "LUCY 14 SLIM lewy BS",
    "LUCY 14 SLIM prawy BS",
    "LUCY 14 tunel",
    "LUCY 16",
    "MAJA 8 DECO",
    "MAJA 8 lewy",
    "MAJA 8 lewy BS",
    "MAJA 8 lewy BS DECO",
    "MAJA 8 prawy",
    "MAJA 8 prawy BS",
    "MAJA 8 prawy BS DECO",
    "MAJA 8",
    "MB 100 gilotyna",
    "MBA 17 gilotyna",
    "MBA 17 lewy BS gilotyna",
    "MBA 17 prawy BS",
    "MBA 17 prawy BS gilotyna",
    "MBM 10 gilotyna",
    "MBM 10 lewy BS gilotyna",
    "MBM 10 prawy BS gilotyna",
    "MBM 10",
    "MBO 15 gilotyna",
    "MBZ 13 lewy BS gilotyna",
    "MBZ 13 prawy BS gilotyna",
    "MBZ 13 prawy BS szyba gięta",
    "MBZ 13",
    "NADIA 10",
    "NADIA 12",
    "NADIA 13",
    "NADIA 13 gilotyna",
    "NADIA 14",
    "NADIA 14 gilotyna",
    "NADIA 14 lewy BS gilotyna",
    "NADIA 14 prawy BS gilotyna",
    "NADIA 8",
    "NADIA 9",
    "OLIWIA 18 DECO",
    "OLIWIA 18",
    "SIMPLE M/S 8 lewy BS",
    "SIMPLE M/S 8 prawy BS",
    "WIKTOR 14 DECO",
    "WIKTOR 14",
    "ZIBI 12 DECO",
    "ZIBI 12 gilotyna",
    "ZIBI 12 lewy BS",
    "ZIBI 12 lewy BS DECO",
    "ZIBI 12 prawy BS",
    "ZIBI 12 prawy BS DECO",
    "ZIBI 12",
    "ZOSIA ECO 12",
    "ZUZIA 16 DECO",
    "ZUZIA ECO 12",
    "ZUZIA ECO 12 DECO",
    "ZUZIA ECO 12 lewy BS DECO",
    "ZUZIA ECO 12 prawy BS DECO",
    "ZUZIA 16 lewy BS",
    "ZUZIA 16 lewy BS DECO",
    "ZUZIA 16 lewy BS gilotyna",
    "ZUZIA 16 prawy BS",
    "ZUZIA 16 prawy BS DECO",
    "ZUZIA 16",
  ],
  "KFD-p": [
    "Linea DF H 1180 3.0",
    "Linea DF V 1190 3.0",
    "Linea DF V 810 3.0",
    "Linea H 1050 3.0",
    "Linea H 1180 3.0",
    "Linea H 1320 3.0 ",
    "Linea H 1570 3.0",
    "Linea H 920 3.0 ",
    "Linea V 1070 3.0",
    "Linea V 1080 3.0 ",
    "Linea V 1190 3.0 ",
    "NAROŻNY KFD ECO iLINE 5161 L/R",
    "NAROŻNY KFD ECO iLINE 5172 L/R",
  ],
  "Romotop-p": [
    "IMPRESSION C 2G L 67.61.34.21",
    "IMPRESSION C 2G L 80.61.34.21",
    "IMPRESSION R/L 2G L 58.60.34.21",
    "IMPRESSION R/L 2G L 71.60.34.21",
    "IMPRESSION R/L 2G L 83.60.34.21",
    "IMPRESSION 2G L 118.60.01",
    "IMPRESSION 2G L 67.60.01",
    "IMPRESSION 2G L 80.60.01",
    "IMPRESSION 2G L 93.60.01",
    "IMPRESSION R/L 2G S 58.60.34.21",
    "IMPRESSION 2G L 118.60.01",
    "IMPRESSION R/L 2G S 71.60.34.21",
    "IMPRESSION 2G 42.60.01",
    "IMPRESSION 2G 55.60.01",
    "IMPRESSION 2G 67.60.01",
    "IMPRESSION 2G 80.60.01",
    "IMPRESSION 2G 67.60.01",
    "IMPRESSION 2G 80.60.01",
    "DYNAMIC 2G 35.46.01",
    "DYNAMIC 2G 44.55.01",
    "DYNAMIC 2G 44.55.13",
    "DYNAMIC 2G 66.50.01",
    "DYNAMIC 2G 66.50.13",
    "DYNAMIC B2G 35.46.01",
    "DYNAMIC B2G 66.50.01",
    "DYNAMIC B2G 66.50.13",
    "DYNAMIC 3G 38.50.01",
    "DYNAMIC 3G 44.55.01",
    "DYNAMIC 3G 66.44.01",
    "DYNAMIC R/L 3G S 55.44.42.21",
    "DYNAMIC R/L 3G S 72.44.42.21",
    "DYNAMIC T 3G 44.55.01",
    "DYNAMIC T 3G 66.44.01",
    "HEAT C 3G L 50.52.31.01(21)",
    "HEAT C 3G L 65.52.31.01(21)",
    "HEAT C 2G L 50.52.31.01(21)",
    "HEAT C 3G L 80.52.31.01(21)",
    "HEAT U 3G L 50.52.50.21",
    "HEAT U 3G L 50.52.70.21",
    "HEAT R/L 3G L 50.51.40.21",
    "HEAT R/L 3G L 65.51.40.01(21)",
    "HEAT R/L 3G L 81.51.40.01(21)",
    "HEAT 3G L 110.50.01",
    "HEAT 3G L 66.50.01",
    "HEAT 3G L 88.50.01",
    "HEAT 3G L 88.66.01",
    "HEAT T 3G 70.50.01",
    "HEAT T 3G L 88.50.01",
    "HEAT R/L 2G S 50.44.33.13(23)",
    "HEAT R/L 2G S 60.44.33.13(23)",
    "HEAT R/L 2G S 65.51.40.01(21)",
    "HEAT R/L 2G S 70.44.33.13(23)",
    "HEAT 2G 42.50.01",
    "HEAT 2G 59.44.13",
    "HEAT 2G 59.50.01",
    "HEAT 2G 59.50.13",
    "HEAT 2G 70.44.01",
    "HEAT 2G 70.44.13",
    "HEAT 2G 70.50.01",
    "HEAT 2G 80.50.01",
  ],
  "Schmid-p": [
    "Lina 45s",
    "Lina 45h",
    "Lina GT 45s",
    "Lina GT 45h",
    "Lina 55s",
    "Lina 55h",
    "Lina 67s",
    "Lina 67h",
    "Lina 6751h Kristall+",
    "Lina TV 6751 h/k Kristall+",
    "Lina 73s",
    "Lina 73h",
    "Lina 7351h Kristall+",
    "Lina 7363h Kristall+",
    "Lina GT 7363h",
    "Lina 87h",
    "Lina 8751h Kristall+",
    "Lina 8757h Kristall+",
    "Lina TV 8751h Kristall+",
    "Lina 8770h",
    "Lina 100h",
    "Lina 10051h",
    "Lina TV 10051h",
    "Lina 120h",
    "Ekko 34s",
    "Ekko 34h",
    "Ekko 45s",
    "Ekko 45h",
    "Ekko 45 80h",
    "Ekko L 55s",
    "Ekko R 67s",
    "Ekko L 55h",
    "Ekko R 55h",
    "Ekko L 67s",
    "Ekko L 67s (ze szprosami)",
    "Ekko L 67h",
    "Ekko R 67s",
    "Ekko R 67s (ze szprosami)",
    "Ekko R 67h",
    "Ekko L 84h",
    "Ekko R 84h",
    "Ekko L 100h",
    "Ekko L 100h (łączona)",
    "Ekko R 100h",
    "Ekko R 100h (łączona)",
    "Ekko U 45",
    "Ekko U 55",
    "Ekko U 67",
    "Ekko U 84",
    "Ekko U 100",
    "Ekko 45(34) 51h Kristall",
    "Ekko 55(45) 51h Kristall",
    "Ekko 55(67) 51h Kristall",
    "Ekko 60(90) 51h Kristall",
    "Ekko 67(45) 51h Kristall",
    "Ekko 84(34) 51h",
    "Ronda 55s",
    "Ronda 55h",
    "Ronda 67s",
    "Ronda 67h",
    "Ronda 180 stopni 6057",
    "Pano 55s",
    "Pano 55h",
    "Pano 67s",
    "Pano 67h",
  ],
  "Spartherm-p": [
    "Premium A-3RL-60h",
    "Premium A-3RL-80h",
    "Premium A-U-70h",
    "Premium V-1V-87h",
    "Premium V-2L-80h",
    "Premium V-2R-80h",
    "Varia 2L-50h-4S",
    "Varia 2R-50h-4S",
    "Mini Z1-7,0 kW-4S",
    "Mini Z1-10,0 kW-4S",
    "Mini S-4S",
    "Mini Sh-4S",
    "Mini R1V",
    "Varia 1V-4S",
    "Varia 1Vh-4S",
    "Varia 1V-100h",
    "Varia 1V-100h-4S",
    "Varia Sh-4S",
    "Varia AS",
    "Varia ASh",
    "Varia Ah-4S",
    "Varia Bh-4S",
    "Varia B-120h-4S",
    "Varia M-60h-4S",
    "Varia M-80h-4S",
    "Varia M-100h-4S",
    "Arte 1Vh-66-4S-2",
    "Arte Bh-4S",
    "Mini S-FDh-4S",
    "Varia FD-4S",
    "Varia FDh-4S",
    "Varia AS-FDh-4S-2",
    "Varia A-FDh-4S",
    "Varia B-FDh-4S",
    "Mini 2L-4S",
    "Mini 2R-4S",
    "Mini 2LRh-4S",
    "Varia 2L-55-4S",
    "Varia 2L-55h-4S",
    "Varia 2Lh",
    "Varia AS-2Lh-4S",
    "Varia 2L-80h-4S",
    "Varia 2L-100h-4S",
    "Varia 2R-55-4S",
    "Varia 2R-55h-4S",
    "Varia 2Rh-4S",
    "Varia AS-2Rh-4S",
    "Varia 2R-80h-4S",
    "Varia 2R-100h-4S",
    "Arte 2LRh-66",
    "Varia AS-3RLh",
    "Varia C-45h-4S",
    "Varia Ch-4S",
    "Arte U-50h-4S",
    "Arte U-70h-4S",
    "Arte U-90h-4S",
    "Arte 3RL-60h-4S",
    "Arte 3RL-80h-4S",
    "Arte 3RL-100h-4S",
    "Speedy MR",
    "Speedy MRh",
    "Speedy  Ph-4S",
    "Magic",
    "Renova B-Air",
    "Renova C-Air",
    "Nova F-Air",
    "Mini R1V-4S RLU",
    "Mini Z1-4S RLU",
    "Mini S-4S RLU",
    "Varia 1V-4S RLU",
    "Varia AS-4S-2 RLU",
    "Varia FD-4S RLU",
    "Varia 2L-55h-4S RLU",
    "Varia 2R-55h-4S RLU",
    "Varia Sh-4S RLU",
    "Cosmo RCH",
    "Cosmo Tunnel RCH",
    "Maestro 75 RCH",
    "Maestro 75 Tunnel",
    "Maestro 75 XTU",
    "Maestro 80/2 RCH",
    "Maestro 80/3 RCH",
    "Metro 100XT RCH",
    "Metro 100XT Tunnel",
    "Metro 130XT RCH",
    "Metro 130XT Tunnel",
    "Metro 150XT RCH",
    "Metro 150XT Tunnel",
    "Metro 200 XT",
    "Metro 80XT RCH",
    "Metro 80XT Tunnel",
    "Metro 100XT/2 RCH",
    "Maestro 105/2 RCH",
    "Metro 130XT/2 RCH",
    "Lugo 70/2 RCH",
    "Lugo 80/2 RCH",
    "Maestro 105/3 RCH",
    "Metro 100XT/3 RCH",
    "Metro 130XT/3 RCH",
    "Metro 100XTL RCH",
    "Metro 130XTL RCH",
    "Metro 100XTU RCH",
    "Lugo 70/3 RCH",
    "Lugo 80/3 RCH",
    "Paco RCE",
    "Global 60XT BF",
    "Global 70XT BF",
    "Global 100 BF",
    "Global 60 BF Corner",
    "Global 60 triple BF",
    "Global 100 BF Corner",
    "Global 100 Triple BF",
    "Global 120 BF",
    "Global 120 BF Corner",
    "Global 120 Triple BF",
  ],
  //Płaszcz wodny
  "Brunner-pw": [
    "Kamin Wasserführend Flach 38/86",
    "Kamin Wasserführend Flach 45/101",
    "Kamin Wasserführend Flach 51/67",
    "Kamin Wasserführend Flach 62/67 Schiebetür",
    "Kamin Wasserführend Eck 57/67/44",
    "Kamin Wasserführend Eck 45/67/44",
    "Kamin Wasserführend Tunnel 38/86",
    "Kamin Wasserführend Tunnel 45/101",
    "Kamin Wasserführend Tunnel 51/67",
  ],
  "Defro-pw": [
    "HOME RIVA SM SHORT",
    "HOME RIVA ME SHORT",
    "HOME RIVA LA SHORT",
    "HOME NAVI SM",
    "HOME NAVI ME",
    "HOME RIVA SM BL SHORT",
    "HOME RIVA ME BL SHORT",
    "HOME RIVA SM BP SHORT",
    "HOME RIVA ME BP SHORT",
    "HOME NAVI SM G",
    "HOME NAVI ME G",
    "HOME RIVA SM G SHORT",
    "HOME RIVA ME G SHORT",
    "HOME RIVA LA G SHORT",
    "HOME RIVA SM BL G SHORT",
    "HOME RIVA ME BL G SHORT",
    "HOME RIVA SM BP G SHORT",
    "HOME RIVA ME BP G SHORT",
  ],
  "Kratki-pw": [
    "AMELIA PW 24 gilotyna",
    "AMELIA PW 24",
    "AMELIA PW 24 DECO",
    "AMELIA PW 24 (podwójna szyba)",
    "AMELIA PW 30 gilotyna",
    "AMELIA PW 30 DECO",
    "AMELIA PW 30 (podwójna szyba)",
    "AMELIA PW 24 lewy BS DECO",
    "AMELIA PW 24 lewy",
    "AMELIA PW 24 prawy BS",
    "AMELIA PW 24 prawy BS DECO",
    "ANTEK PW 8 gilotyna",
    "ANTEK PW 8 DECO",
    "AQUARIO A14 PW",
    "AQUARIO A14 PW GLASS",
    "AQUARIO A18 PW",
    "AQUARIO A18 PW GLASS",
    "AQUARIO M12 PW",
    "AQUARIO M12 PW GLASS",
    "AQUARIO M8 PW",
    "AQUARIO M8 PW GLASS",
    "AQUARIO O12 PW",
    "AQUARIO O12 PW GLASS",
    "AQUARIO O16 PW",
    "AQUARIO O16 PW GLASS",
    "AQUARIO Z10 PW",
    "AQUARIO Z10 PW GLASS",
    "AQUARIO Z14 PW",
    "AQUARIO Z 14 PW GLASS",
    "ERYK PW 10 DECO",
    "FELIX PW 14 gilotyna",
    "FELIX PW 14 DECO",
    "FRANEK PW 12",
    "LUCY PW 12 (podwójna szyba)",
    "LUCY PW 16",
    "LUCY PW 16 (podwójna szyba)",
    "LUCY PW 20",
    "LUCY PW 20 (podwójna szyba)",
    "MAJA 8 gilotyna",
    "MAJA PW 12 DECO",
    "MAJA PW 12 lewy BS DECO",
    "MAJA PW 12 prawy BS DECO",
    "MAJA PW 12 prawy",
    "MBA PW 17 gilotyna",
    "MBA PW 17",
    "MBM PW 10 gilotyna",
    "MBM PW 10 lewy BS",
    "MBM PW 10",
    "MBO PW 15 gilotyna",
    "MBO PW 15 lewy BS",
    "MBO PW 15 prawy BS",
    "MBO PW 15",
    "MBZ PW 13 gilotyna",
    "MBZ PW 13 gilotyna (podwójna szyba)",
    "MBZ gilotyna z wężownica czarny",
    "MBZ PW 13",
    "MBZ PW 13 (podwójna szyba)",
    "MILA PW 24 gilotyna",
    "MILA PW 24 gilotyna (podwójna szyba)",
    "MILA PW 24",
    "NADIA PW 10",
    "OLIWIA PW 17 gilotyna",
    "OLIWIA PW 17 DECO",
    "OLIWIA PW 22 gilotyna",
    "OLIWIA PW 22 DECO",
    "OLIWIA PW 17 lewy BS DECO",
    "OLIWIA PW 17 lewy",
    "OLIWIA PW 22 lewy BS DECO",
    "OLIWIA PW 22 lewy",
    "OLIWIA PW 17 prawy BS DECO",
    "OLIWIA PW 17 prawy",
    "OLIWIA PW 22 prawy BS DECO",
    "OLIWIA PW 22 prawy",
    "WIKTOR PW 12 DECO",
    "WIKTOR PW 12 gilotyna",
    "ZUZIA PW 15 gilotyna",
    "ZUZIA PW 15 DECO",
    "ZUZIA PW 19 gilotyna",
    "ZUZIA PW 19 DECO",
    "ZUZIA PW 15 lewy BS DECO",
    "ZUZIA PW 19 lewy BS DECO",
    "ZUZIA PW 19 lewy",
    "ZUZIA PW 15 prawy BS DECO",
    "ZUZIA PW 15 prawy",
    "ZUZIA PW 19 prawy BS",
    "ZUZIA PW 19 prawy BS DECO",
    "ZUZIA PW 19 tunel",
    "AMELIA PW 30",
    "AMELIA PW 24 lewy BS",
    "AMELIA PW 24 prawy",
    "ANTEK PW 8",
    "FELIX PW 14",
    "MAJA PW 12 gilotyna",
    "MAJA PW 12",
    "MAJA PW 12 lewy BS",
    "MAJA PW 12 lewy",
    "MAJA PW 12 prawy BS",
    "MBA PW 17 lewy BS",
    "MBA PW 17 prawy BS",
    "MBM PW 10 prawy BS",
    "MBZ PW 13 lewy BS",
    "MBZ PW 13 prawy BS",
    "OLIWIA PW 17",
    "OLIWIA PW 22",
    "OLIWIA PW 17 lewy BS",
    "OLIWIA PW 22 lewy BS",
    "OLIWIA PW 17 prawy BS",
    "OLIWIA PW 22 prawy BS",
    "ZUZIA PW 15",
    "ZUZIA PW 19",
    "ZUZIA PW 15 lewy BS",
    "ZUZIA PW 15 lewy",
    "ZUZIA PW 19 lewy BS",
    "ZUZIA PW 15 prawy BS",
    "ZUZIA PW 19 prawy",
    "LUCY PW 12",
  ],
  "Schmid-pw": [
    "Lina W 6751s",
    "Lina W 6751h",
    "Lina W 7363s",
    "Lina W 7363h",
    "Ekko W L 67(45)51 s (ze szprosem)",
    "Ekko W R 67(45)51 s (ze szprosem)",
    "Ekko W L 67(45)51 s (bez szprosa)",
    "Ekko W R 67(45)51 s (bez szprosa)",
    "Ekko W L 67(45)51 h",
    "Ekko W R (67(45)51 h",
  ],
  "Spartherm-pw": [
    "Varia 1V H2O-4S",
    "Varia 1Vh H2O-4S",
    "Varia 1V H2O XL-4S",
    "Varia 1Vh H2O XL-4S",
    "Varia 1V H2O XXL-4S",
    "Varia 1Vh H2O XXL-4S",
    "Varia 1VX H2O-4S",
    "Varia 1VXh H2O-4S",
    "Varia Ah H2O-4S",
    "Varia FD H2O-4S",
    "Varia FDh H2O-4S",
    "Varia A-FDh H2O-4S",
    "Varia 2L-55h H2O-4S",
    "Varia 2Lh H2O-4S",
    "Varia 2R-55h H2O-4S",
    "Varia 2Rh H2O-4S",
    "Nova E H2O",
    "Renova A H2O",
  ],
  "Romotop-pw": [
    "DYNAMIC W 2G 66.50.01",
    "DYNAMIC W 2G 66.50.01P",
    "DYNAMIC WB 2G 66.50.01",
    "DYNAMIC WB 2G 66.50.01P",
    "HEAT W 2G 59.50.01",
    "HEAT W 2G 70.50.01",
  ],
};
